[package]
name = "dasm"
version = "0.1.0"
publish = false
edition = "2018"

[[bin]]
name = "ftohex"
path = "src/ftohex.rs"

[dependencies]
lazy_static = "1.4.0"
libc = "0.2"
num_enum = "0.5.0"
smart-default = "0.6.0"

[profile.release]
lto = true
panic = 'abort'
